version: 2
jobs:
  test:
    docker:
      - image: node:10.16.3-buster
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            npm install -g apify-cli
            npm test    
  deploy:
    docker:
      - image: node:10.16.3-buster
    steps:
      - checkout
      - run:
          name: Install deployment dependencies
          command: |
            npm add global apify-cli
      - run:
          name: Deploying
          command: |
            apify login --token ${APIFY_TOKEN}
            apify push  
workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - test