version: 2
jobs:
  test:
    docker:
      - image: apify/actor-node-chrome
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            npm install
            npm test    
  deploy:
    docker:
      - image: node:10.16.3-buster
    steps:
      - checkout
      - run:
          name: Installing deployment dependencies
          command: |
            npm install -g apify-cli
      - run:
          name: Deploying
          command: |
            apify login --token ${APIFY_TOKEN}
            apify push --build-tag ${CIRCLE_BRANCH} --version ${CIRCLE_SHA1}
workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - test